-- i18n: locales, UI strings, entity translations, page translations, mail templates.
--
-- All translation tables are composite-PK (namespace + key + locale + field)
-- rather than autogenerated IDs — the natural key is the lookup path.

CREATE TABLE IF NOT EXISTS locales (
    code        TEXT PRIMARY KEY,
    name        TEXT NOT NULL,
    is_default  BOOLEAN NOT NULL DEFAULT FALSE,
    enabled     BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order  INTEGER NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Seed default locales. Without this, every page that uses useAdminLocales()
-- spins forever waiting for a locale list to populate, and the framework's
-- I18nConfig.FallbackLocales is only used until the DB has rows.
-- ON CONFLICT DO NOTHING keeps this idempotent if the runner re-applies.
INSERT INTO locales (code, name, is_default, enabled, sort_order) VALUES
    ('de', 'Deutsch', TRUE,  TRUE, 0),
    ('en', 'English', FALSE, TRUE, 1)
ON CONFLICT (code) DO NOTHING;

-- All four translation tables FK their `locale` column to locales(code) with
-- ON DELETE CASCADE. Removing a locale should also drop its dead translation
-- rows (otherwise they're orphan storage that no admin UI surfaces).

-- UI-string translations (e.g. "auth.login_subject" -> "Your login link").
CREATE TABLE IF NOT EXISTS locale_translations (
    locale      TEXT NOT NULL REFERENCES locales(code) ON DELETE CASCADE,
    key         TEXT NOT NULL,
    value       TEXT NOT NULL DEFAULT '',
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (locale, key)
);

-- Entity translations: per-row per-field translations for domain entities
-- (apps, projects, screenshots, versions). entity_type + entity_id scope
-- the row; (locale, field) picks the translated string.
CREATE TABLE IF NOT EXISTS entity_translations (
    entity_type TEXT NOT NULL,
    entity_id   TEXT NOT NULL,
    locale      TEXT NOT NULL REFERENCES locales(code) ON DELETE CASCADE,
    field       TEXT NOT NULL,
    value       TEXT NOT NULL DEFAULT '',
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (entity_type, entity_id, locale, field)
);

CREATE INDEX IF NOT EXISTS idx_entity_translations_type_locale
    ON entity_translations(entity_type, locale);

-- Page translations: per-page per-field translations for static pages
-- (legal, landing copy, etc.).
CREATE TABLE IF NOT EXISTS page_translations (
    page_key    TEXT NOT NULL,
    locale      TEXT NOT NULL REFERENCES locales(code) ON DELETE CASCADE,
    field       TEXT NOT NULL,
    value       TEXT NOT NULL DEFAULT '',
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (page_key, locale, field)
);

CREATE INDEX IF NOT EXISTS idx_page_translations_locale
    ON page_translations(locale);

-- Mail templates: per-locale subject/body pairs keyed by a template name.
CREATE TABLE IF NOT EXISTS mail_templates (
    locale      TEXT NOT NULL REFERENCES locales(code) ON DELETE CASCADE,
    template    TEXT NOT NULL,
    subject     TEXT NOT NULL DEFAULT '',
    body        TEXT NOT NULL DEFAULT '',
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (locale, template)
);
