-- Authentication: magic-link tokens and session storage.
-- Both tables use TEXT primary keys (opaque random strings generated by the
-- app) so we don't depend on a Postgres UUID extension at the framework level.

-- user_type and (in sessions) user_id are NULLABLE on purpose: callers that
-- don't supply a TokenOption pass *string=nil, which pgx serializes as NULL.
-- Adding NOT NULL would break the optional-hint semantic.
CREATE TABLE IF NOT EXISTS auth_tokens (
    token       TEXT PRIMARY KEY,
    email       TEXT NOT NULL,
    expires_at  TIMESTAMPTZ NOT NULL,
    used        BOOLEAN NOT NULL DEFAULT FALSE,
    user_type   TEXT
);

CREATE INDEX IF NOT EXISTS idx_auth_tokens_email ON auth_tokens(email);
CREATE INDEX IF NOT EXISTS idx_auth_tokens_expires ON auth_tokens(expires_at);

CREATE TABLE IF NOT EXISTS sessions (
    id          TEXT PRIMARY KEY,
    email       TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at  TIMESTAMPTZ NOT NULL,
    user_id     TEXT,
    user_type   TEXT
);

CREATE INDEX IF NOT EXISTS idx_sessions_email ON sessions(email);
CREATE INDEX IF NOT EXISTS idx_sessions_expires ON sessions(expires_at);
